tests:
  - name: Part 1 Sample 1
    config: p1_sample1.yaml
    expected_result: 40
  - name: Part 1
    config: part1.yaml
    expected_result: 527
  - name: Part 2 Sample 1
    config: p2_sample1.yaml
    expected_result: 315
  - name: Part 2
    config: part2.yaml
    expected_result: 2887
config:
  show_errors: true
