tests:
  - name: Part 1 Sample 1
    config: p1_sample1.yaml
    expected_result: 45
  - name: Part 1
    config: part1.yaml
    expected_result: 5995
config:
  show_errors: true
  enable_printing: true
