tests:
  - name: Part 1 Sample 1
    config: p1_sample1.yaml
    expected_result: 5934
  - name: Part 1
    config: part1.yaml
    expected_result: 371379
  - name: Part 2 Sample 1
    config: p2_sample1.yaml
    expected_result: 26984457539
  - name: Part 2
    config: part2.yaml
    expected_result: 1674303997472
config:
  show_errors: true
  enable_printing: true
