tests:
  - name: Day 11 Part 1 Number of Octopus flashes
    config: day11/part1.yaml
    expected_result: 0
  - name: Day 11 Part 2 When do all Octopi flash
    config: day11/part2.yaml
    expected_result: 0
  - name: Day 12 Part 1 Find all paths through caves
    config: day12/part1.yaml
    expected_result: 0
  - name: Day 12 Part 2 Find all paths with extra repeated caves
    config: day12/part2.yaml
    expected_result: 0
