name: test

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./gradlew ktlintCheck
        working-directory: aoc2023

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: tools/encrypt_files.sh decrypt
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
      - run: ./gradlew test
        working-directory: aoc2023
